import fs from "node:fs";
import path from "node:path";

import type { DocsProjectConfig } from "./types.ts";

function titleCase(str: string): string {
  return str.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

interface AutogenCategory {
  type: "category";
  label: string;
  items: [{ type: "autogenerated"; dirName: string }];
}

export function generateSidebarContent(
  docsDir: string,
  config: DocsProjectConfig,
): string {
  const dirs = fs
    .readdirSync(docsDir, { withFileTypes: true })
    .filter(
      (d) =>
        d.isDirectory() &&
        !d.name.startsWith(".") &&
        !["node_modules", "src", "static", "build"].includes(d.name),
    )
    .map((d) => d.name);

  const order = config.sidebar?.order ?? [];
  const orderedDirs = [
    ...order.filter((d) => dirs.includes(d)),
    ...dirs.filter((d) => !order.includes(d)),
  ];

  const sections: unknown[] = [];

  if (fs.existsSync(path.join(docsDir, "index.md"))) {
    sections.push("index");
  }

  for (const dir of orderedDirs) {
    const label = config.sidebar?.labels?.[dir] ?? titleCase(dir);

    // Check the directory has any markdown files (recursively)
    const dirPath = path.join(docsDir, dir);
    if (!hasMdFiles(dirPath)) continue;

    const category: AutogenCategory = {
      type: "category",
      label,
      items: [{ type: "autogenerated", dirName: dir }],
    };
    sections.push(category);
  }

  const json = JSON.stringify({ docs: sections }, null, 2);

  return `const sidebars = ${json};

export default sidebars;
`;
}

function hasMdFiles(dir: string): boolean {
  if (!fs.existsSync(dir)) return false;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (hasMdFiles(path.join(dir, entry.name))) return true;
    } else if (entry.name.endsWith(".md") || entry.name.endsWith(".mdx")) {
      return true;
    }
  }
  return false;
}
